### ISSUE TITLE
Unable to include generated component

### ISSUE THREAD

**Issue by joshafeinberg** [evant/kotlin-inject#284]
I have a code generator that creates a component. When I try to include that component in my other component I get a compiler error

```
[ksp] java.lang.IllegalStateException: Required value was null.
	at com.squareup.kotlinpoet.ksp.UtilsKt.toClassNameInternal(utils.kt:63)
	at com.squareup.kotlinpoet.ksp.KsClassDeclarationsKt.toClassName(ksClassDeclarations.kt:24)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:66)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:150)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName$default(ksTypes.kt:147)
	at me.tatarka.kotlin.ast.KSAstType.toTypeName(KSAst.kt:464)
	at me.tatarka.kotlin.ast.AstParam.toParameterSpec(Ast.kt:224)
	at me.tatarka.inject.compiler.InjectGenerator.generateInjectComponent(InjectGenerator.kt:106)
	at me.tatarka.inject.compiler.InjectGenerator.generate(InjectGenerator.kt:61)
	at me.tatarka.inject.compiler.ksp.InjectProcessor.process(InjectProcessor.kt:64)
	at me.tatarka.inject.compiler.ksp.InjectProcessor.process(InjectProcessor.kt:52)
```

Code:

```
@Component
internal abstract class AppComponent(@Component val generatedComponent: GeneratedComponent) {

}
```

This occurs even if `GeneratedComponent` is empty

```
package mypackage

import me.tatarka.inject.annotations.Component

@Component
internal abstract class CircuitComponent {
}
```

I have also tested removing the `internal` on the generated component and that also does not solve it

**Comment by nrobi144** [comment]
Getting the same with `[KOTLIN] Kotlin compilation 'jdkHome' argument: null`

**Comment by evant** [comment]
How are you generating that component? If it's with ksp it should work though it's possible there's a bug in gen with multiple rounds, otherwise the issue is the same as https://github.com/evant/kotlin-inject/issues/155 and there isn't a good work-around other than to wrap your generated class in another class.
