### ISSUE TITLE
Question: multiple interfaces and one implementation

### ISSUE THREAD

**Issue by sobotkami** [evant/kotlin-inject#386]
Hi all, I am struggling with this design: ONE adapter implements TWO interfaces. How do I define this correctly? Thanks!

```kotlin 
interface UserReadPort {
    fun findAll(): Set<UserEntity>
    fun findById(id: UserId): UserEntity?
}

interface UserWritePort {
    fun addUser(user: UserEntity)
    fun remove(id: UserId)
    fun removeAll()
}

@Inject
class UserInMemoryAdapter : UserReadPort, UserWritePort { // ...

@Inject
class CreateUserUseCase(lazyUserWritePort: Lazy<UserWritePort>, lazyUserReadPort: Lazy<UserReadPort>) {
    private val userWritePort by lazyUserWritePort
    private val userReadPort by lazyUserReadPort

@Component
abstract class AppComponent(private val port: Int) {
    abstract val createUserUseCase: CreateUserUseCase

    @Provides
    fun userReadInMemoryAdapter(userReadPort: UserReadPort): UserReadPort = userReadPort

    @Provides
    fun userWriteInMemoryAdapter(userWritePort: UserWritePort): UserWritePort = userWritePort
    

```

produces

```
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property userWritePort has not been initialized
	at InjectAppComponent$createUserUseCase$1.invoke(InjectAppComponent.kt:15)
	at InjectAppComponent$createUserUseCase$1.invoke(InjectAppComponent.kt:11)
...
```

Generated code

```kotlin

public fun KClass<AppComponent>.create(port: Int): AppComponent = InjectAppComponent(port)

public class InjectAppComponent(
  port: Int,
) : AppComponent(port) {
  override val createUserUseCase: CreateUserUseCase
    get() = CreateUserUseCase(
      lazyUserWritePort = lazy {
        run<UserWritePort> {
          lateinit var userWritePort: UserWritePort
          userWriteInMemoryAdapter(
            userWritePort = userWritePort
          ).also {
            userWritePort = it
          }
        }

      },
      lazyUserReadPort = lazy {
        run<UserReadPort> {
          lateinit var userReadPort: UserReadPort
          userReadInMemoryAdapter(
            userReadPort = userReadPort
          ).also {
            userReadPort = it
          }
        }

      }
    )
}
```

**Comment by sobotkami** [comment]
One possible solution:

```kotlin
protected val UserInMemoryAdapter.bindRead: UserReadPort
    @Provides get() = this

protected val UserInMemoryAdapter.bindWrite: UserWritePort
    @Provides get() = this
```

But, is there a solution to get rid of these definitions?

**Comment by evant** [comment]
```kotlin
fun userReadInMemoryAdapter(userReadPort: UserReadPort): UserReadPort = userReadPort
```

You are requesting a dependency to provide itself. This should actually fail to compile with a cycle error, the fact it generates invalid code instead is a bug

As you note below, 

```kotlin
protected val UserInMemoryAdapter.bindRead: UserReadPort
    @Provides get() = this
```
Is the correct way to do this, providing the impl to the interface. The equivlent using the function syntax you used originally would be

```kotlin
fun userReadInMemoryAdapter(userReadPort: UserInMemoryAdapter): UserReadPort = userReadPort
```

> But, is there a solution to get rid of these definitions?

No, you need a definition in your component for each interface you are providing. There have been some requests for an [anvil-like](https://github.com/square/anvil?tab=readme-ov-file#contributed-bindings) feature to provide them with an annotation on the class itself instead of the component, https://github.com/evant/kotlin-inject/issues/212 if you are curious.

**Comment by evant** [comment]
Adding the bug label for the invalid code gen. This is likely related to https://github.com/evant/kotlin-inject/issues/313
