### ISSUE TITLE
Incremental compilation sometimes fails with exception

### ISSUE THREAD

**Issue by sergeshustoff** [evant/kotlin-inject#404]
Sometimes after making some small changes and rerunning a single integration test in kotlin-inject repo I get this error. Next run then passes (I suspect it isn't incremental anymore). Seen this in other project using kotlin-inject too

    [ksp] java.io.IOException: java.lang.NegativeArraySizeException: -939472384
	    at org.jetbrains.kotlin.com.intellij.util.io.IOUtil.readString(IOUtil.java:48)
	    at com.google.devtools.ksp.common.FileExternalizer.read(PersistentMap.kt:52)
	    at com.google.devtools.ksp.common.FileExternalizer.read(PersistentMap.kt:51)
	    at com.google.devtools.ksp.common.ListExternalizer.read(PersistentMap.kt:72)
	    at com.google.devtools.ksp.common.ListExternalizer.read(PersistentMap.kt:59)
	    at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:608)
	    at org.jetbrains.kotlin.com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:545)
	    at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:178)
	    at com.google.devtools.ksp.common.DirtinessPropagator.<init>(IncrementalContextBase.kt:533)
	    at com.google.devtools.ksp.common.IncrementalContextBase.calcDirtyFiles(IncrementalContextBase.kt:269)
	    at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$2.invoke(KotlinSymbolProcessingExtension.kt:196)
	    at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$2.invoke(KotlinSymbolProcessingExtension.kt:189)
	    at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
	    at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:189)
	    at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:112)
	    at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:75)
	    at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze$lambda$12(KotlinToJVMBytecodeCompiler.kt:373)
	    at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	    at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:364)
	    at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.runFrontendAndGenerateIrUsingClassicFrontend(KotlinToJVMBytecodeCompiler.kt:195)
	    at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:106)
	    at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:176)
	    at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	    at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	    at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	    at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	    at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1556)
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	    at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	    at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	    at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	    at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	    at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	    at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	    at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	    at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	    at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	    at java.base/java.lang.Thread.run(Thread.java:840)
    Caused by: java.lang.NegativeArraySizeException: -939472384
	    at org.jetbrains.kotlin.com.intellij.util.io.IOUtil.readString(IOUtil.java:40)
	    ... 43 more

**Comment by evant** [comment]
Hm, I don't even see kotlin-inject in the stacktrace, may be worth opening on https://github.com/google/ksp as well

**Comment by sergeshustoff** [comment]
I can't reproduce this anymore, looks like the problem was in some cache or something like that. Will reopen and report to ksp repo as well if it repeats
